### PR TITLE
Using API week2

### PR DESCRIPTION
**Pull request by MadyanNassar**

### CODE REVIEW

**Comment by remarcmij** [comment]
PR to wrong repo

**Comment by MadyanNassar** [comment]
Oh ,, this is my mistake,
sorry I will fix it and make new PR

**Comment by MadyanNassar** [comment]
Hi Jim,
this is the link for correct PR

https://github.com/MadyanNassar/Homework/pull/7

**Comment by remarcmij** [comment]
Hi @MadyanNassar, just update (edit) the issue and replace the link.

**Comment by MadyanNassar** [comment]
Thank you Jim,
i did it

**Pull request closed without merging**
