### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by thibaudszy**
To fix vulnerability warnings from npm audit

### CODE REVIEW

**Comment by hikmetdag** [comment]
Dear Thibaudszy thank you very much for your time , I pushed my homework by mistake to the Homework section, I changed it to Homework class39. This fork is closed. The things that you emphasised  are very new to me. First time I have seen these words.  I will try to google What these things are about :)

**Comment by thibaudszy** [comment]
@hikmetdag this pull request is not linked to your homework, so you can ignore it

**Comment by thibaudszy** [comment]
I'm assuming here that we don't want to track the `package-lock.json` but let me know if we have a reason to

**Comment by robvk** [comment]
I think we do want to keep the `package-lock.json` in there so we can be sure the students have exactly the same versions as us when we tested that they work

**Comment by thibaudszy** [comment]
My understanding was that the package-lock.json changes based on the OS. I looked it up and it's a bit more complicated than this but I'm not sure that npm install generates the same output for students running Windows than for those using MacOS

**Review by robvk — APPROVED** [review]

**Pull request merged**
